# Generated by Django 4.1.5 on 2023-03-03 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_categories', models.CharField(max_length=25, unique=True)),
                ('Copune_code', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'Shop_categories',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Shop_products')),
                ('Product_name', models.CharField(max_length=25, unique=True)),
                ('Discount_price', models.FloatField()),
                ('Actual_price', models.FloatField()),
                ('Rate', models.PositiveIntegerField(blank=True, default=0)),
                ('product_details', models.JSONField()),
                ('quantity', models.PositiveBigIntegerField(blank=True, default='0')),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.shop_categories')),
            ],
            options={
                'db_table': 'Shop',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.JSONField()),
                ('addby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.shop')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
