# Generated by Django 4.1.5 on 2023-03-03 05:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submited_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Submitted_cards')),
                ('Card_name', models.CharField(max_length=50)),
                ('Year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('Card_No', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Rarity', models.CharField(max_length=25)),
                ('Declared_Amt', models.PositiveBigIntegerField()),
                ('Service_type', models.CharField(max_length=30)),
                ('Recived', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Submited_Cards',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='Grading_card_Img')),
                ('NFC_No', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('Card_Name', models.CharField(max_length=25)),
                ('Card_No', models.CharField(max_length=10)),
                ('Rarity', models.CharField(max_length=25)),
                ('Year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('Series', models.CharField(max_length=25)),
                ('Game', models.CharField(max_length=25)),
                ('Overall_Grade', models.CharField(max_length=10)),
                ('Centering', models.FloatField()),
                ('Surface', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('Edges', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('Corners', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('Notes', models.CharField(max_length=20)),
                ('shop', models.BooleanField()),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Card',
            },
        ),
    ]
